# Generated by Django 4.1.10 on 2023-10-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclenum', models.CharField(default='', max_length=50)),
                ('model', models.CharField(default='', max_length=50)),
                ('brand', models.CharField(default='', max_length=50)),
                ('manfyear', models.CharField(default='', max_length=50)),
                ('color', models.CharField(default='', max_length=50)),
                ('ownername', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('phNum', models.CharField(default='', max_length=50)),
                ('image', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
